### ISSUE TITLE
Failed to load remote context https://linkedsoftwaredependencies.org/bundles/npm/solid-calendar-store/^0.0.0/components/context.jsonld: Internal Server Error

### ISSUE THREAD

**Issue by junszhao** [KNowledgeOnWebScale/solid-calendar-store#18]
HI,

I used the sample config file as instructed in the README. All seem well, however, when I was tried to access my server, the folllowing error log appeared:

022-02-18T13:17:38.843Z [Components.js] warn: Detected remote context lookup for 'https://linkedsoftwaredependencies.org/bundles/npm/solid-calendar-store/^0.0.0/components/context.jsonld' in /home/ubuntu/workspace/community-server/config-cal.json. This may indicate a missing or invalid dependency, or an invalid context URL.
2022-02-18T13:17:38.907Z [Components.js] warn: Detected remote context lookup for 'https://linkedsoftwaredependencies.org/bundles/npm/@rmlio/solid-rml-store/^0.0.0/components/context.jsonld' in /home/ubuntu/workspace/community-server/config-cal.json. This may indicate a missing or invalid dependency, or an invalid context URL.
Error: could not instantiate server from /home/ubuntu/workspace/community-server/config-cal.json
Error: Error while parsing file "/home/ubuntu/workspace/community-server/config-cal.json": Failed to load remote context https://linkedsoftwaredependencies.org/bundles/npm/solid-calendar-store/^0.0.0/components/context.jsonld: Internal Server Error
    at Function.addPathToError (/home/ubuntu/.npm/_npx/519be4cd80562143/node_modules/componentsjs/lib/rdf/RdfParser.js:73:16)
    at PassThrough.<anonymous> (/home/ubuntu/.npm/_npx/519be4cd80562143/node_modules/componentsjs/lib/rdf/RdfParser.js:46:38)
    at PassThrough.emit (node:events:402:35)
    at JsonLdParser.<anonymous> (/home/ubuntu/.npm/_npx/519be4cd80562143/node_modules/rdf-parse/lib/RdfParser.js:71:47)
    at JsonLdParser.emit (node:events:402:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

It looks like a depedency issue. The jsonld file cannot be found in the given URL. Should a different version be used and updated in the config file?

Many thanks.

**Comment by pheyvaer** [comment]
Hi @junszhao 

Thanks for the issue! This issue can happen when CSS can't find the Solid Calendar Store. How are you starting the CSS and where is it installed?
